name       : notmuch
version    : 0.29.1
release    : 11
source     :
    - https://github.com/notmuch/notmuch/archive/0.29.1.tar.gz : 6872a2ff760f413635146b36be01840bfeaeaaecebf1fb5817be0320fd21aae5
homepage   : http://notmuchmail.org/
license    : GPL-3.0-or-later
component  : network.mail
summary    : Just an email system
description: |
    Notmuch is a mail indexer. Essentially, is a very thin front end on top of xapian. It focuses on one thing: indexing your email messages. Notmuch can be used as an email reader, or simply as an indexer and search tool for other MUAs, like mutt.
builddeps  :
    - pkgconfig(ruby-2.6)
    - pkgconfig(python3)
    - pkgconfig(xapian-core)
    - pkgconfig(gmime-3.0)
    - pkgconfig(talloc)
    - python-sphinx
rundeps    :
    - gnupg
setup      : |
    %configure
build      : |
    %make
    cd bindings/python
    python2 setup.py build
    python3 setup.py build
install    : |
    %make_install
    make -C bindings/ruby exec_prefix=$installdir prefix=/usr install
    make -C vim DESTDIR=$installdir prefix=/usr/share/vim/addons install
    cd bindings/python
    python2 setup.py install --root=$installdir --no-compile
    python3 setup.py install --root=$installdir --no-compile
