name       : notmuch
version    : 0.27
release    : 5
source     :
    - https://notmuchmail.org/releases/notmuch-0.27.tar.gz : 40d3192f8f130f227b511fc80be86310c7f60ccb6d043b563f201fa505de0876
homepage   : http://notmuchmail.org/
license    : GPL-3.0
component  : network.mail
summary    : Just an email system
description: |
    Notmuch is a mail indexer. Essentially, is a very thin front end on top of xapian. It focuses on one thing: indexing your email messages. Notmuch can be used as an email reader, or simply as an indexer and search tool for other MUAs, like mutt.
builddeps  :
    - pkgconfig(ruby-2.3)
    - pkgconfig(python3)
    - pkgconfig(xapian-core)
    - pkgconfig(gmime-3.0)
    - pkgconfig(talloc)
    - python-sphinx
rundeps    :
    - gnupg
setup      : |
    %configure
build      : |
    %make
    cd bindings/python
    python2 setup.py build
    python3 setup.py build
install    : |
    %make_install
    make -C bindings/ruby exec_prefix=$installdir prefix=/usr install
    make -C vim DESTDIR=$installdir prefix=/usr/share/vim/addons install
    cd bindings/python
    python2 setup.py install --root=$installdir --no-compile
    python3 setup.py install --root=$installdir --no-compile
