name       : notmuch
version    : 0.28.3
release    : 9
source     :
    - https://github.com/notmuch/notmuch/archive/0.28.3.tar.gz : ce3287c2ea9ed315e7d3e7d066e33189b9edb2e459e125881135c7def159193b
homepage   : http://notmuchmail.org/
license    : GPL-3.0-or-later
component  : network.mail
summary    : Just an email system
description: |
    Notmuch is a mail indexer. Essentially, is a very thin front end on top of xapian. It focuses on one thing: indexing your email messages. Notmuch can be used as an email reader, or simply as an indexer and search tool for other MUAs, like mutt.
builddeps  :
    - pkgconfig(ruby-2.6)
    - pkgconfig(python3)
    - pkgconfig(xapian-core)
    - pkgconfig(gmime-3.0)
    - pkgconfig(talloc)
    - python-sphinx
rundeps    :
    - gnupg
setup      : |
    %configure
build      : |
    %make
    cd bindings/python
    python2 setup.py build
    python3 setup.py build
install    : |
    %make_install
    make -C bindings/ruby exec_prefix=$installdir prefix=/usr install
    make -C vim DESTDIR=$installdir prefix=/usr/share/vim/addons install
    cd bindings/python
    python2 setup.py install --root=$installdir --no-compile
    python3 setup.py install --root=$installdir --no-compile
